In [ ]:
# Numpy:-
# Exercises for Practice
# 1. Create a 3×3 array filled with random numbers and print its shape.
# 2. Convert an array of floats [1.1, 2.2, 3.3] into integers.
# 4. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
# 5. Reshape a 1D array of size 9 into a 3×3 matrix.
# 6. Use boolean masking to filter numbers greater than 50 in an array

In [ ]:
# 1. Create a 3×3 array filled with random numbers and print its shape.
import numpy as np
import random
np.zeros((3,4))
np.ones((3,3))
np.ones(5)
np.full((3,3),7)
np.eye(7)
np.arange(1,99,5)
np.linspace(1,99,7)
np.random.rand(3) #gives float values between 0 and 1
np.random.randint(0,999,(3,3))




array([[627, 423,  57],
       [348, 467, 660],
       [951,  12,  36]])

In [ ]:
#Convert an array of floats [1.1, 2.2, 3.3] into integers.

import numpy as np
import random
arr = np.array(np.random.randint(0,10,(3,3)), dtype=np.float32)
print("Original array:-\n",arr)

print("\nInteger form:-\n",arr.astype(int))
# arr = arr.astype(int)

print("\nOG:-\n ", arr)




Original array:-
 [[7. 0. 5.]
 [2. 0. 8.]
 [7. 7. 3.]]

Integer form:-
 [[7 0 5]
 [2 0 8]
 [7 7 3]]

OG:-
  [[7 0 5]
 [2 0 8]
 [7 7 3]]


In [90]:
# 3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

import numpy as np
import random as rd

arr = np.array(np.random.randint(1,10,(10)))
print(arr)

print("\nPicking even numbers from the given array.\n")
even = arr[arr%2 == 0]
print(even)
print(arr)

[6 5 8 8 7 9 4 9 9 1]

Picking even numbers from the given array.

[6 8 8 4]
[6 5 8 8 7 9 4 9 9 1]


In [93]:
#4. Reshape a 1D array of size 9 into a 3×3 matrix.

import numpy as np
import random 

arr = np.array(np.random.randint(1,99,(9)))
print(arr)
arr.reshape((3,3))

[43 30 59 20 82 47 79 28 41]


array([[43, 30, 59],
       [20, 82, 47],
       [79, 28, 41]])

In [98]:
# 5. Use boolean masking to filter numbers greater than 50 in an array.

import numpy as np
import random

arr = np.array(np.random.randint(1,100,(99)))
print(arr)
mask = arr[arr>50]
print("\nMasked array of values greater than 50:-\n",mask)

[53 68 28 80 95 89 90 24 53 97 68 45 15 54 41 57 39 14 75 60 68 81 74  9
 86 61  8 21 19 75 65 47 24 33 47 91 16 85 31 14 56 87 55 19 21 87 26 23
 61 31 12 45 58  4 15 52 36 28 53 90 92 84 20 46 39 95 15  5 28 95 94 57
 59 67 34 28 26 49 53 71 78 24 59 61 10 84 97 77 93 45 58 89 58 63 82 79
 45 50 22]

Masked array of values greater than 50:-
 [53 68 80 95 89 90 53 97 68 54 57 75 60 68 81 74 86 61 75 65 91 85 56 87
 55 87 61 58 52 53 90 92 84 95 95 94 57 59 67 53 71 78 59 61 84 97 77 93
 58 89 58 63 82 79]
