In [22]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
print(arr[1])
print(arr[1][2])
print(arr[-2][2]) #same as python lisṭ̣̣

print("Slicing :-")
print( "Original array:-\n",arr)
print(arr[1:2])
print(arr[0, 0:2])
print(arr[1][1:3])
#Use .copy() if you need an independent copy.

# Fancy Indexing 
arr2 = np.array([12,23,34,45,56,67])
x = [1,3,5]
print(arr2[x])

# Boolean Masking (Filtering)
arr3 = np.array([13,24,35,46,57,68], dtype=np.float32)
print("Arr3 :- ", arr3)
mask = arr3 > 25
print(arr3[mask])



[4 5 6]
6
3
Slicing :-
Original array:-
 [[1 2 3]
 [4 5 6]]
[[4 5 6]]
[1 2]
[5 6]
[23 45 67]
Arr3 :-  [13. 24. 35. 46. 57. 68.]
[35. 46. 57. 68.]
