In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr1,"\n",arr2)
print(arr2)


[1 2 3 4 5] 
 [[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
#Creating arrays from scratch
import numpy as np
np.zeros(3)
np.ones((4,4))
np.zeros((4,3))
np.full((2,2),12)
np.eye(5)
np.arange(1,19,2)
np.linspace(1,199,21)

# np.zeros((3, 3))    # 3x3 array of zeros
# np.ones((2, 4))     # 2x4 array of ones
# np.full((2, 2), 7)  # 2x2 array filled with 7
# np.eye(4)           # 4x4 identity matrix
# np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (like range)
# np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
# 2. Checking array properties

arr = np.array([[1,2,3],[5,7,6]])
print("Shape", arr.shape)
print("Size:", arr.size)
print("Dimensions", arr.ndim)
print("Data type:", arr.dtype)

Shape (2, 3)
Size: 6
Dimensions 2
Data type: int64


In [40]:
# 3. Changing Data Types

import numpy as np

arr= np.array([1,2.7,3],dtype=np.float32)
print(arr.dtype)
print(arr)

arr_int = arr.astype(np.int32)
print(arr_int)


arr = arr.astype(np.int32)
print(arr)


float32
[1.  2.7 3. ]
[1 2 3]
[1 2 3]


In [ ]:
# 4. Reshaping and flattening arrays
arr = np.array([11,22,33,44,55,66,77,88])
print(arr)
print("Now we do the reshapping:-")
reshaped = arr.reshape((2,4))
print(reshaped)

print("It's the original array:-\n",arr)
print("Now we do the flattening of the array:-")
flattened = arr.flatten() # Convert 2D -> 1D
print(flattened)




[11 22 33 44 55 66 77 88]
Now we do the reshapping:-
[[11 22 33 44]
 [55 66 77 88]]
It's the original array:-
 [11 22 33 44 55 66 77 88]
Now we do the flattening of the array:-
[11 22 33 44 55 66 77 88]
